#!/bin/bash
#
echo "Criando a imagem 'glpi-apache-php82'..."
docker build -f Dockerfile-glpi -t glpi-apache-php82 .

if docker container ls | grep -q "glpi-web"; then
   docker contatiner stop glpi_html && \
      docker container rm glpi_html
else
   if docker container ls -a | grep -q "glpi-web"; then
      docker contatiner stop glpi-web && \
         docker container rm glpi-web
   fi
fi
 docker run -d \
  -p 8080:80 \
  --name glpi-web \
  --network glpi-net \
  -v glpi_html:/var/www/html \
glpi-apache-php82




