version: "3.8"

services:
  glpi:
    image: diouxx/glpi
    container_name: glpi
    depends_on:
      - db
    ports:
      - "8080:80"
    environment:
      TIMEZONE: America/Sao_Paulo
    volumes:
      - glpi_data:/var/www/html
    restart: unless-stopped

  db:
    image: mariadb:10.5
    container_name: glpi_db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: glpidb
      MYSQL_USER: glpi
      MYSQL_PASSWORD: glpi
    volumes:
      - db_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: glpi_phpmyadmin
    restart: unless-stopped
    ports:
      - "8081:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root

volumes:
  glpi_data:
  db_data:

